#!/bin/bash
#
# Copyright (c) 2026 Eclipse Oniro for OpenHarmony contributors.
# SPDX-License-Identifier: Apache-2.0
#
# Regenerate the libbinder_ndk AIDL client/server code for the Android
# radio HAL, version 2 — the interface set the Halium 14 container's
# mtkfusionrild publishes on this device (verified in
# /android/vendor/etc/vintf/manifest.xml).
#
# The generated tree is CHECKED IN so the OHOS build needs neither the
# `aidl` compiler nor an AOSP checkout.  Re-run this only to move to a
# different frozen version or to add a package.
#
# Inputs (both fetched, not vendored — see PROVENANCE.md):
#   AIDL      path to AOSP's aidl compiler (Android SDK build-tools >= 33,
#             e.g. build-tools_r34-linux.zip -> android-14/aidl)
#   AOSP_RADIO  path to a checkout/export of
#             platform/hardware/interfaces/radio  (android14-release)
#
# Usage:
#   AIDL=~/android-sdk/build-tools/34.0.0/aidl \
#   AOSP_RADIO=~/aosp/hardware/interfaces/radio \
#   ./regen.sh
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AIDL="${AIDL:?set AIDL=<path to aidl compiler>}"
AOSP_RADIO="${AOSP_RADIO:?set AOSP_RADIO=<path to hardware/interfaces/radio>}"
API="$AOSP_RADIO/aidl_api"

# Every package the container publishes, with the frozen version it
# publishes it at (checked against /android/vendor/etc/vintf/manifest.xml
# and the *-ndk.so set in /android/vendor/lib64).  Most are v2; `ims` is
# frozen at v1 only.
#
# `ims` is not optional even though nothing here implements IMS.  MTK's
# rild only treats the framework as connected once setResponseFunctions
# has been called on *all seven* per-slot AOSP radio interfaces — see
# rilAidlUtils::checkIfSetAllAospResponseDone() in librilfusion.so, and
# plan §10 — and until then it refuses to deliver MT SMS.  So the client
# has to be able to register on ims as well, if only with a stub.
#
# `ims.media` and `sap` are genuinely out of scope: they are not part of
# that count.
V2_PKGS=(
  android.hardware.radio
  android.hardware.radio.config
  android.hardware.radio.data
  android.hardware.radio.messaging
  android.hardware.radio.modem
  android.hardware.radio.network
  android.hardware.radio.sim
  android.hardware.radio.voice
)
V1_PKGS=(
  android.hardware.radio.ims
)

# Include paths cover every package at its own version: the v1 ims
# interfaces import v2 base types (RadioResponseInfo and friends), which
# is exactly how the device's own libraries are built.
INCS=()
for p in "${V2_PKGS[@]}"; do
    [ -d "$API/$p/2" ] || { echo "missing $API/$p/2" >&2; exit 1; }
    INCS+=(-I "$API/$p/2")
done
for p in "${V1_PKGS[@]}"; do
    [ -d "$API/$p/1" ] || { echo "missing $API/$p/1" >&2; exit 1; }
    INCS+=(-I "$API/$p/1")
done

rm -rf "$HERE/src" "$HERE/include"
mkdir -p "$HERE/src" "$HERE/include"

# --stability=vintf matches the @VintfStability annotation the frozen
# snapshots carry; without it the generated proxies refuse to talk to a
# vintf-stable server.  --min_sdk_version only gates __INTRODUCED_IN
# guards in the generated code.  --version applies to every input of one
# invocation, so the two version groups are compiled separately.
gen_group() {
    local version="$1"; shift
    local srcs=()
    local p
    for p in "$@"; do
        while IFS= read -r f; do srcs+=("$f"); done \
            < <(find "$API/$p/$version" -name '*.aidl' | sort)
    done
    "$AIDL" --lang=ndk --structured --stability=vintf \
            --version="$version" --min_sdk_version=31 \
            "${INCS[@]}" \
            --out="$HERE/src" --header_out="$HERE/include" \
            "${srcs[@]}"
}

gen_group 2 "${V2_PKGS[@]}"
gen_group 1 "${V1_PKGS[@]}"

# GN cannot glob, so publish the file list the build imports.
{
    cat <<'EOF'
# Copyright (c) 2026 Eclipse Oniro for OpenHarmony contributors.
# SPDX-License-Identifier: Apache-2.0
#
# GENERATED by regen.sh — do not edit.

radio_aidl_sources = [
EOF
    (cd "$HERE" && find src -name '*.cpp' | sort | sed 's|^|  "aidl_gen/|; s|$|",|')
    echo "]"
} > "$HERE/sources.gni"

echo "generated $(find "$HERE/src" -name '*.cpp' | wc -l) sources, \
$(find "$HERE/include" -name '*.h' | wc -l) headers, sources.gni"
