#!/bin/bash
#
# Copyright (c) 2026 Eclipse Oniro for OpenHarmony contributors.
# SPDX-License-Identifier: Apache-2.0
#
# Regenerate the libbinder_ndk AIDL client/server code for the Android
# radio HAL, version 2 — the interface set the Halium 14 container's
# mtkfusionrild publishes on this device (verified in
# /android/vendor/etc/vintf/manifest.xml).
#
# The generated tree is CHECKED IN so the OHOS build needs neither the
# `aidl` compiler nor an AOSP checkout.  Re-run this only to move to a
# different frozen version or to add a package.
#
# Inputs (both fetched, not vendored — see PROVENANCE.md):
#   AIDL      path to AOSP's aidl compiler (Android SDK build-tools >= 33,
#             e.g. build-tools_r34-linux.zip -> android-14/aidl)
#   AOSP_RADIO  path to a checkout/export of
#             platform/hardware/interfaces/radio  (android14-release)
#
# Usage:
#   AIDL=~/android-sdk/build-tools/34.0.0/aidl \
#   AOSP_RADIO=~/aosp/hardware/interfaces/radio \
#   ./regen.sh
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AIDL="${AIDL:?set AIDL=<path to aidl compiler>}"
AOSP_RADIO="${AOSP_RADIO:?set AOSP_RADIO=<path to hardware/interfaces/radio>}"
API="$AOSP_RADIO/aidl_api"
VERSION=2

# Every package the container publishes at v2.  `ims`, `ims.media` and `sap`
# are frozen at v1 only and are out of scope for R0-R7 (plan §D8) — add them
# here if R8 needs them.
PKGS=(
  android.hardware.radio
  android.hardware.radio.config
  android.hardware.radio.data
  android.hardware.radio.messaging
  android.hardware.radio.modem
  android.hardware.radio.network
  android.hardware.radio.sim
  android.hardware.radio.voice
)

INCS=()
for p in "${PKGS[@]}"; do
    [ -d "$API/$p/$VERSION" ] || { echo "missing $API/$p/$VERSION" >&2; exit 1; }
    INCS+=(-I "$API/$p/$VERSION")
done

rm -rf "$HERE/src" "$HERE/include"
mkdir -p "$HERE/src" "$HERE/include"

SRCS=()
for p in "${PKGS[@]}"; do
    while IFS= read -r f; do SRCS+=("$f"); done \
        < <(find "$API/$p/$VERSION" -name '*.aidl' | sort)
done

# --stability=vintf matches the @VintfStability annotation the frozen
# snapshots carry; without it the generated proxies refuse to talk to a
# vintf-stable server.  --min_sdk_version only gates __INTRODUCED_IN
# guards in the generated code.
"$AIDL" --lang=ndk --structured --stability=vintf \
        --version="$VERSION" --min_sdk_version=31 \
        "${INCS[@]}" \
        --out="$HERE/src" --header_out="$HERE/include" \
        "${SRCS[@]}"

# GN cannot glob, so publish the file list the build imports.
{
    cat <<'EOF'
# Copyright (c) 2026 Eclipse Oniro for OpenHarmony contributors.
# SPDX-License-Identifier: Apache-2.0
#
# GENERATED by regen.sh — do not edit.

radio_aidl_sources = [
EOF
    (cd "$HERE" && find src -name '*.cpp' | sort | sed 's|^|  "aidl_gen/|; s|$|",|')
    echo "]"
} > "$HERE/sources.gni"

echo "generated $(find "$HERE/src" -name '*.cpp' | wc -l) sources, \
$(find "$HERE/include" -name '*.h' | wc -l) headers, sources.gni"
