#!/bin/bash
#
# Copyright (c) 2026 Eclipse Oniro for OpenHarmony contributors.
# SPDX-License-Identifier: Apache-2.0
#
# Emit the aarch64 tail-jump trampolines that let AOSP-generated AIDL code
# — which is compiled for OHOS/musl but calls libbinder_ndk's C ABI — reach
# the Halium container's bionic libbinder_ndk.so through libhybris.
#
# One stub per symbol:
#
#     NAME:  adrp x16, g_hybris_binder_ndk_fn
#            add  x16, x16, :lo12:g_hybris_binder_ndk_fn
#            ldr  x16, [x16, #IDX*8]
#            br   x16
#
# A tail jump through a pointer is signature-agnostic: every argument stays
# in the register or stack slot the caller put it in, x8 (indirect result)
# is untouched, and x16/x17 are the AAPCS64 intra-procedure-call scratch
# registers, so clobbering them across the branch is legal.  That is why
# 142 different prototypes need no per-symbol knowledge at all.
#
# Inputs:  binder_ndk_symbols.txt — the C-ABI exports of the container's
#          libbinder_ndk.so (`nm -D --defined-only`, filtered to the
#          A{IBinder,Parcel,Status,ServiceManager}_/ABinderProcess_ prefixes).
# Outputs: binder_ndk_trampolines.S, binder_ndk_symbols.inc  (both checked in)
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIST="$HERE/binder_ndk_symbols.txt"
ASM="$HERE/binder_ndk_trampolines.S"
INC="$HERE/binder_ndk_symbols.inc"

mapfile -t SYMS < <(grep -vE '^\s*(#|$)' "$LIST")

hdr() {
    cat <<EOF
/*
 * Copyright (c) 2026 Eclipse Oniro for OpenHarmony contributors.
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by gen_trampolines.sh from binder_ndk_symbols.txt — do not edit.
 */
EOF
}

{
    hdr
    cat <<'EOF'

#if defined(__aarch64__)

    .text

    /* Slot table, defined with hidden visibility in hybris_binder_ndk.cpp so
     * these adrp/:lo12: references resolve without a GOT indirection. */
    .hidden g_hybris_binder_ndk_fn

.macro  ndk_stub name, idx
    .balign 4
    .globl  \name
    .type   \name, %function
\name:
    adrp    x16, g_hybris_binder_ndk_fn
    add     x16, x16, :lo12:g_hybris_binder_ndk_fn
    ldr     x16, [x16, #(8 * \idx)]
    br      x16
    .size   \name, . - \name
.endm

EOF
    i=0
    for s in "${SYMS[@]}"; do
        echo "    ndk_stub $s, $i"
        i=$((i + 1))
    done
    cat <<'EOF'

#else
#error "binder_ndk trampolines are aarch64-only"
#endif

    .section .note.GNU-stack,"",%progbits
EOF
} > "$ASM"

{
    hdr
    echo
    echo "/* Order MUST match binder_ndk_trampolines.S slot indices. */"
    for s in "${SYMS[@]}"; do
        echo "HYBRIS_BINDER_NDK_SYM(\"$s\")"
    done
} > "$INC"

echo "wrote ${#SYMS[@]} trampolines -> $(basename "$ASM"), $(basename "$INC")"
